name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            runtime: linux-x64
          - os: windows-latest
            runtime: win-x64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal

    - name: Publish VersionInfo
      run: dotnet publish VersionInfo/VersionInfo.csproj --configuration Release /p:DebugType=none /p:StripSymbols=true --output ./publish/VersionInfo

    - name: Publish SimpleGui
      run: dotnet publish SimpleGui/SimpleGui.csproj --configuration Release --runtime ${{ matrix.runtime }} --self-contained true /p:DebugType=none /p:StripSymbols=true --output ./publish/SimpleGui

    - name: Upload VersionInfo artifacts
      uses: actions/upload-artifact@v4
      with:
        name: VersionInfo-${{ matrix.runtime }}
        path: ./publish/VersionInfo
        retention-days: 7

    - name: Upload SimpleGui artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SimpleGui-${{ matrix.runtime }}
        path: ./publish/SimpleGui
        retention-days: 7
